# Generated by Django 4.2 on 2023-05-30 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_orders_alter_students_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_discount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_place_at',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_quantity',
        ),
        migrations.AddField(
            model_name='orders',
            name='oders_address',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='oders_discount',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='oders_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='oders_place_at',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='oders_quantity',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='oders_time',
            field=models.TimeField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1),
        ),
        migrations.CreateModel(
            name='StudentsAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=15, null=True)),
                ('house_number', models.IntegerField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('pin_code', models.IntegerField(blank=True, max_length=15, null=True)),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
        ),
    ]
